DROP TABLE IF EXISTS employee, project, employee_project_position, position, customer CASCADE;

CREATE TABLE IF NOT EXISTS position
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_type VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS employee
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS project
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS customer
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    responsible_id BIGINT,
    FOREIGN KEY (responsible_id) REFERENCES employee (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS employee_project_position
(
    employee_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE,
    FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE,
    PRIMARY KEY (employee_id, position_id, project_id)
);